### ISSUE TITLE
Publish NPM

### ISSUE THREAD

**Issue by lukeed** [bucaran/fly-mocha#3]
No access to NPM

**Comment by lukeed** [comment]
@jbucaran

**Comment by pine** [comment]
Hi @lukeed. I'll publish to npm.

**Comment by lukeed** [comment]
Oh, I forgot this was yours. Great, thanks! It's already tagged & versioned.

**Comment by pine** [comment]
I've just published to npm. Thanks.

**Comment by pine** [comment]
https://www.npmjs.com/package/fly-mocha

**Comment by lukeed** [comment]
Thanks @pine
